---
- hosts: all
  sudo: yes
  tasks:
  - name: Install node js latest version
    package:
        name: nodejs
        enablerepo: epel
        state: latest
  - name: Check the node version
    raw: node -v
    register: output
  - debug: var=output.stdout